Box the Simulator
Yaya-Cout/Upsilon-Workshop pull request #37
Opened 2023-06-14 15:46 UTC by BloomyInDev

2023-06-14 15:50 UTC, Yaya-Cout requested changes

2023-06-14 15:50 UTC, Yaya-Cout commented on src/routes/Viewer.vue
> +    launchSimul() {
Don't use abbreviations
```suggestion
    launchSimulator() {
```

2023-06-14 15:50 UTC, Yaya-Cout commented on src/routes/Viewer.vue
> +      startSimul: false
Same
```suggestion
      startSimulator: false
```

2023-06-14 15:50 UTC, Yaya-Cout commented on src/locales/fr.json
> +    "simulator-stop":"Stopper le simulateur"
```suggestion
    "simulator-launch": "Lancer le simulateur",
    "simulator-stop": "Stopper le simulateur"
```

2023-06-14 15:51 UTC, BloomyInDev commented on src/routes/Viewer.vue
> +    launchSimul() {
Sry

2023-06-20 14:24 UTC, Yaya-Cout requested changes
You have to rename the other variables to match the rename

2023-09-24 10:39 UTC, closed without merging